language: node_js
node_js:
  - 8
before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_b9bd228152b0_key
    -iv $encrypted_b9bd228152b0_iv
    -in patternplate-deploy.enc
    -out patternplate-deploy -d
  - chmod 600 patternplate-deploy
  - eval $(ssh-agent -s)
  - ssh-add patternplate-deploy
  - rm patternplate-deploy
script:
  - yarn lerna build
  - yarn components:build
  - yarn components:deploy
