language: node_js
node_js:
  - 8
script:
  - yarn test --stream
jobs:
  include:
    - stage: deploy
      script:
        - yarn build --scope=@patternplate/{cli,components} --include-filtered-dependencies --stream
        - yarn components:build --stream
      before_deploy:
        - ./.travis/decrypt.sh
      deploy:
        - ./.travis/deploy.sh
