language: node_js
node_js:
  - 8
jobs:
  include:
    - stage: test
      script:
        - yarn test --stream
      script:
        - yarn build --scope=@patternplate/{cli,components} --include-filtered-dependencies --stream
        - yarn components:build --stream
      before_deploy:
        - ./.travis/decrypt.sh
      deploy:
        skip_cleanup: true
        - provider: script
          script: bash ./.travis/deploy.sh
          on:
            branch: master
