language: node_js
before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_b9bd228152b0_key
    -iv $encrypted_b9bd228152b0_iv
    -in patternplate-deploy.enc
    -out patternplate-deploy -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
script:
  - yarn components:build
  - yarn components:deploy
